### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by macaba** [macaba/NSD#1]
Features requested from initial users:

- [x] Input: require both "Acquisition time" and "Data rate" input (so that 1/f corner is correctly positioned for sparse datasets)
- [x] Input: directory selector
- [x] Input: skip first n rows, select value column
- [ ] Chart: configurable title & legend
- [ ] Chart: add to chart (multiple trends)
- [ ] Chart: tooltips (if possible; to display noise value at particular frequency)

**Comment by 952895776** [comment]
Is it convenient to generate an exe file
